//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by actor.rc
//
#define IDCANCEL2                       3
#define ID_BTN_FAPPLY                   3
#define IDR_ACCELERATOR1                105
#define IDD_DIALOGMBASSIGN              106
#define IDC_CURSOR1                     107
#define IDC_CURSORGRUB                  107
#define IDD_DIALOGFRAME                 108
#define IDD_DIALOGABOUT                 109
#define IDD_DIALOGACOPY                 110
#define IDB_BITMAP1                     111
#define IDB_BITMAPCCW                   111
#define IDB_BITMAPCW                    112
#define IDD_DIALOGPRIOR                 113
#define IDD_DIALOGSOUND                 114
#define IDC_RADIO_FDEL                  1005
#define IDC_RADIO_FCOPY                 1006
#define IDC_RADIO_FSWAP                 1007
#define IDC_ABOUTBUILD                  1008
#define IDC_EDIT1                       1009
#define ID_APPLYA                       1010
#define ID_CLOSEA                       1011
#define IDC_RBACCCW                     1012
#define IDC_RBACCW                      1013
#define IDC_RBACDETAIL                  1014
#define IDC_CBAC11                      1015
#define IDC_CBAC2                       1016
#define IDC_CBAC3                       1017
#define IDC_CBAC12                      1018
#define IDC_RADIOAC0                    1019
#define IDC_RADIOAC1                    1020
#define IDC_RADIOAC2                    1021
#define IDC_RADIOAC3                    1022
#define IDC_RADIOAC4                    1023
#define IDC_RADIOAC5                    1024
#define IDC_RADIOAC6                    1025
#define IDC_RADIOAC7                    1026
#define IDC_RADIOHEADFRONT              1027
#define IDC_RADIOHEADBACK               1028
#define IDC_RADIOBODYFRONT              1029
#define IDC_RADIOBODYBACK               1030
#define IDC_RADIOETCFRONT               1031
#define IDC_RADIOETCBACK                1032
#define IDC_RADIONEIGHFRONT             1033
#define IDC_RADIONEIGHBACK              1034
#define IDC_FELABEL1                    1035
#define IDC_FELABEL2                    1036
#define IDC_FELABEL3                    1037
#define IDC_FELABEL4                    1038
#define IDC_ACDLABEL1                   1039
#define IDC_ACDLABEL2                   1040
#define IDC_ACDLABEL3                   1041
#define IDC_ACDLABEL4                   1042
#define IDC_ACDLABEL5                   1043
#define IDC_ACDLABEL6                   1044
#define IDC_ACDLABEL7                   1045
#define IDC_ACDLABEL8                   1046
#define IDC_ACDLABEL9                   1047
#define IDC_ACDLABEL10                  1048
#define IDC_ACDLABEL11                  1049
#define IDC_GRLABEL1                    1050
#define IDC_GRLABEL2                    1051
#define IDC_GRLABEL3                    1052
#define IDC_GRPLABEL1                   1053
#define IDC_GRPLABEL2                   1054
#define IDC_GRPLABEL3                   1055
#define IDC_GRPLABEL4                   1056
#define IDC_ABOUTLABEL1                 1057
#define IDC_ABOUTLABEL2                 1058
#define IDC_SPIN_FDEL                   2002
#define IDC_EDIT_FDEL                   2003
#define IDC_SPIN_FCOPY                  2004
#define IDC_EDIT_FCOPY                  2005
#define IDC_SPIN_FSWAP1                 2006
#define IDC_EDIT_FSWAP1                 2007
#define IDC_SPIN_FSWAP2                 2008
#define IDC_EDIT_FSWAP2                 2009
#define IDC_RADIO1                      2101
#define IDC_RADIO2                      2102
#define IDC_RADIO3                      2103
#define IDC_RADIO4                      2104
#define IDC_RADIO5                      2105
#define IDC_RADIO6                      2106
#define IDC_RADIO7                      2107
#define IDC_RADIO8                      2108
#define IDC_RADIO9                      2109
#define IDC_RADIOAC10                   2110
#define IDC_RADIOAC11                   2111
#define IDC_RADIOAC12                   2112
#define IDC_RADIOAC13                   2113
#define IDC_RADIOAC14                   2114
#define IDC_RADIOAC15                   2115
#define IDC_RADIOAC16                   2116
#define IDC_RADIOAC17                   2117
#define IDC_EDITINTER                   2118
#define IDC_CBSND                       2119
#define IDC_LIST_SOUND                  2120
#define IDC_BTN_SADD                    2122
#define IDC_BTN_SDEL                    2123
#define IDC_BTN_SUP                     2124
#define IDC_BUTTON2                     2125
#define IDC_BTN_SDOWN                   2125
#define IDC_ABOUTLABEL3                 2126
#define IDM_EXIT                        40005
#define IDM_READ                        40006
#define IDM_WRITEBMP                    40007
#define IDM_WRITESPR                    40008
#define IDM_REPLACEIMAGE                40009
#define IDM_WRITE1IMAGE                 40011
#define ID_Menu                         40012
#define IDM_WRITEACT                    40015
#define IDM_COLSELBG                    40021
#define IDM_COLSELSEL                   40022
#define IDM_COLSELLINE                  40023
#define IDM_MBASSIGN                    40024
#define IDM_HORIZON                     40027
#define IDM_VERTICAL                    40028
#define IDM_SATRPLUS                    40030
#define IDM_SATRMINUS                   40034
#define IDM_SATGPLUS                    40038
#define IDM_SATGMINUS                   40039
#define IDM_SATBPLUS                    40047
#define IDM_SATBMINUS                   40048
#define IDM_SATAPLUS                    40049
#define IDM_SATAMINUS                   40050
#define IDM_MIRRORCHANGE                40051
#define IDM_FRAMEEDIT                   40060
#define IDM_PALLETSAME                  40062
#define IDM_INSERTBEFORE                40066
#define IDM_INSERTAFTER                 40069
#define IDM_DELETEIMAGE                 40072
#define IDM_UNDO                        40076
#define IDM_REDO                        40077
#define IDM_ABOUT                       40081
#define IDM_ACTCOPY                     40083
#define IDM_WRITEACTTEXT                40085
#define IDM_PRIORREFSPR                 40086
#define IDM_FILE                        40087
#define IDM_AUDIT                       40090
#define IDM_NEXTFRAME                   40093
#define IDM_PREVFRAME                   40094
#define IDM_SOUND                       40095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40096
#define _APS_NEXT_CONTROL_VALUE         2127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
